### ISSUE TITLE
Kill text

### ISSUE THREAD

**Issue by AlchlcDvl** [MyDragonBreath/AmongUs.MultiClientInstancing#1]
3 main issues that I've noticed:-

When switching between roles with and without kill buttons, sometimes the "Kill" text will transfer over to the buttons of the role without the kill button.

Continuing with the previous issue, the button art gets weird and it starts to go darker and darker until it becomes pitch black just behind the kill text. Both this and the previous issue can be seen in the embedded video on the GitHub page

The last one is well the recent Among Us update. I know this mod isn't updated to it but yeah it works. The problem is that when spawning the beans, they are invisible. But the mod works fine on 8.24

**Comment by MyDragonBreath** [comment]
Will work on fixing

**Comment by MyDragonBreath** [comment]
1 - fixed in :dev
2 - seems to be fixed in :dev
3 - fixed itself.....
