### ISSUE TITLE
Broken as of Among Us v2024.6.18

### ISSUE THREAD

**Issue by ItzLoonie** [MyDragonBreath/AmongUs.MultiClientInstancing#22]
Innersloth changed a lot of things, which broke this utility.

**Comment by MyDragonBreath** [comment]
not surprising ill get round to fixing it

**Comment by AmongUsafk** [comment]
> not surprising ill get round to fixing it

It seems that Innersloth changed how players are spawned in the newest version because The `CreatePlayer` now is `IEnumerator` in `AmongUsClient`

**Comment by AmongUsafk** [comment]
@ItzLoonie MCI has upgraded and now Support AU 2024.6.18 check actions tab and dev branch

**Comment by Night-GUA** [comment]
no,i still can't use it

**Comment by Night-GUA** [comment]
I am sorry,I clone another version...

**Comment by AmongUsafk** [comment]
> no,i still can't use it


> I am sorry,I clone another version...

np have fun testing your mods!
